application:
  subdomain: portabase
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://portabase-app:80/
services:
  db:
    # docker.io/library/postgres:16-alpine
    # upstream: docker.io/library/postgres:16.14-alpine3.24
    image: registry.lazycat.cloud/czyt/library/postgres:a379d12d223884d8
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD={{ stable_secret "db_password" }}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U devuser -d devdb
      interval: 10s
      timeout: 5s
      retries: 5
    binds:
      - /lzcapp/var/data:/var/lib/postgresql/data
    cpu_shares: 512
    mem_limit: 512M
  portabase-app:
    # docker.io/portabase/portabase:1.2.4
    # upstream: docker.io/portabase/portabase:1.28.1
    image: registry.lazycat.cloud/czyt/portabase/portabase:1ea97a7b348fc403
    environment:
      - TZ={{.U.timezone}}
      - NODE_ENV=production
      - DATABASE_URL=postgresql://devuser:{{ stable_secret "db_password" }}@db:5432/devdb?schema=public
      - PROJECT_NAME=Portabase
      - PROJECT_DESCRIPTION=Portabase is a powerful database manager
      - PROJECT_URL=https://${LAZYCAT_APP_DOMAIN}
      - PROJECT_SECRET={{ stable_secret "project_secret" }}
      - RETENTION_CRON=* * * * *
    depends_on:
      - db
    cpu_shares: 1024
    mem_limit: 1024M
